# Generated by Django 4.2 on 2023-06-12 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OmuraMuseum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('satisfaction', models.IntegerField()),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('stay_time', models.FloatField()),
                ('wait_time', models.IntegerField(default=0)),
                ('explain', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('museumname', models.CharField(max_length=100)),
                ('time', models.IntegerField(default=60)),
                ('speed', models.IntegerField(default=80)),
                ('browse', models.FloatField(default=1.0)),
                ('path', models.CharField(default='0, 7, 16, 14, 2, 1, 3, 4, 5, 10, 8, 6, 0', max_length=1000)),
                ('now_spot', models.IntegerField(default=0)),
                ('next_spot', models.IntegerField(default=1)),
                ('predict_time', models.FloatField(default=0)),
                ('now_time', models.FloatField(default=0)),
                ('calculate_count', models.IntegerField(default=0)),
            ],
        ),
    ]
