# Generated by Django 4.2 on 2023-07-03 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QAmuseum', '0002_userpath_count_alter_userpath_browse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='omuramuseum',
            name='satisfaction',
            field=models.FloatField(),
        ),
    ]
