# Generated by Django 4.2 on 2023-07-03 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QAmuseum', '0003_alter_omuramuseum_satisfaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='omuramuseum',
            old_name='explain',
            new_name='exp',
        ),
    ]
