# Generated by Django 4.2 on 2023-07-30 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QAmuseum', '0005_museumimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MuseumImage',
        ),
    ]
