# Generated by Django 4.2 on 2023-07-30 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QAmuseum', '0007_museumimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='museumimage',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
