# Generated by Django 4.2 on 2023-07-30 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QAmuseum', '0008_alter_museumimage_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='omuramuseum',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
