# Generated by Django 4.2 on 2023-07-30 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QAmuseum', '0009_alter_omuramuseum_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='museumimage',
            name='name',
            field=models.CharField(default='入口', max_length=100),
        ),
    ]
