# Generated by Django 4.2 on 2023-07-30 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QAmuseum', '0010_museumimage_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='omuramuseum',
            name='image',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
