# Generated by Django 4.2 on 2023-07-30 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QAmuseum', '0011_omuramuseum_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='museumimage',
            name='image',
            field=models.ImageField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='omuramuseum',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
    ]
