# Generated by Django 4.2 on 2023-07-31 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QAmuseum', '0012_alter_museumimage_image_alter_omuramuseum_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpath',
            name='speed',
            field=models.IntegerField(choices=[(80, '速い'), (70, '普通'), (60, '遅い')], default=80),
        ),
    ]
