# Generated by Django 4.2 on 2023-07-31 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QAmuseum', '0013_alter_userpath_speed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpath',
            name='speed',
            field=models.IntegerField(choices=[(80, '速い'), (70, '普通'), (60, '遅い')], default=70),
        ),
    ]
