# Generated by Django 4.2 on 2023-07-31 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QAmuseum', '0014_alter_userpath_speed'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpath',
            name='start_time',
            field=models.FloatField(default=0),
        ),
    ]
