# Generated by Django 4.2 on 2023-07-31 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QAmuseum', '0015_userpath_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpath',
            name='speed',
            field=models.IntegerField(choices=[(70, '速い'), (60, '普通'), (50, '遅い')], default=60),
        ),
    ]
