# Generated by Django 4.2 on 2023-08-01 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QAmuseum', '0016_alter_userpath_speed'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpath',
            name='visit_path',
            field=models.CharField(default='0', max_length=1000),
        ),
    ]
