# Generated by Django 4.2 on 2023-08-02 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QAmuseum', '0017_userpath_visit_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpath',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
