# Generated by Django 4.2 on 2023-08-02 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QAmuseum', '0018_alter_userpath_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpath',
            name='goal_time',
            field=models.IntegerField(default=0),
        ),
    ]
