# Generated by Django 4.2 on 2023-08-02 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QAmuseum', '0019_userpath_goal_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpath',
            name='goal_time',
            field=models.FloatField(default=0),
        ),
    ]
