# Generated by Django 4.2 on 2023-08-02 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QAmuseum', '0020_alter_userpath_goal_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpath',
            name='goal_time',
            field=models.IntegerField(default=0),
        ),
    ]
