# Generated by Django 4.2 on 2023-08-03 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QAmuseum', '0021_alter_userpath_goal_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='MuseumEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_id', models.IntegerField(default=0)),
                ('display_name', models.CharField(max_length=100)),
                ('display_evaluation', models.ImageField(default=0, upload_to='')),
                ('user_name', models.CharField(max_length=20)),
            ],
        ),
    ]
