# Generated by Django 4.2 on 2023-08-08 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QAmuseum', '0023_alter_museumevaluation_display_evaluation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpath',
            name='time',
            field=models.IntegerField(default=40),
        ),
    ]
