# Generated by Django 4.2 on 2023-08-10 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QAmuseum', '0024_alter_userpath_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='museumevaluation',
            name='display_time',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='userpath',
            name='caluculate_back',
            field=models.IntegerField(default=0),
        ),
    ]
