# Generated by Django 4.2 on 2023-08-21 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QAmuseum', '0025_museumevaluation_display_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpath',
            name='caluculate_back',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
