# Generated by Django 4.2 on 2023-08-21 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QAmuseum', '0026_alter_userpath_caluculate_back'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpath',
            name='calc_bool',
            field=models.BooleanField(default=False),
        ),
    ]
