# Generated by Django 4.2 on 2023-11-27 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QAmuseum', '0028_userpath_count_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='omuramuseum',
            name='en_exp',
            field=models.TextField(default='text'),
        ),
        migrations.AddField(
            model_name='omuramuseum',
            name='en_name',
            field=models.CharField(default='title', max_length=100),
        ),
    ]
