# Generated by Django 4.2 on 2023-11-27 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QAmuseum', '0029_omuramuseum_en_exp_omuramuseum_en_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpath',
            name='last_page',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='userpath',
            name='password',
            field=models.CharField(default='QA', max_length=10),
        ),
    ]
