# Generated by Django 4.2 on 2023-11-27 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QAmuseum', '0030_userpath_last_page_userpath_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpath',
            name='password',
            field=models.CharField(default='', max_length=10),
        ),
    ]
