# Generated by Django 4.2 on 2023-12-11 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QAmuseum', '0031_alter_userpath_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpath',
            name='must_spot',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='userpath',
            name='password',
            field=models.CharField(default='', max_length=8),
        ),
    ]
