# Generated by Django 4.2 on 2023-12-11 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QAmuseum', '0032_userpath_must_spot_alter_userpath_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='omuramuseum',
            name='map_image',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
    ]
