# Generated by Django 4.2 on 2023-12-11 07:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QAmuseum', '0033_omuramuseum_map_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpath',
            name='password',
            field=models.CharField(default='', max_length=4, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
    ]
